package com.roze.smarthr.enums;

public enum NotificationType {
    LEAVE,
    ATTENDANCE,
    BIRTHDAY,
    HOLIDAY,
    TRAINING,
    ANNOUNCEMENT,
    SHIFT,
    PAYROLL,
    SYSTEM,
    TRAINING_ENROLLMENT,
    TRAINING_REMINDER,
    TRAINING_COMPLETION,
    TRAINING_FEEDBACK_REQUEST,
    TRAINING_CERTIFICATE_ISSUED,
    TRAINING_CANCELLATION
}